/** ControlIds — names match docs/04 exactly. */

export const CONTROL_IDS = [
  'deckA.play',
  'deckA.cue',
  'deckA.sync',
  'deckA.load',
  'deckA.pfl',
  'deckA.jog',
  'deckA.filter',
  'deckA.wet',
  'deckA.filterPad',
  'deckA.flangerPad',
  'deckA.pitch',
  'deckA.gain',
  'deckA.eqHigh',
  'deckA.eqMid',
  'deckA.eqLow',
  'deckA.killHigh',
  'deckA.killMid',
  'deckA.killLow',
  'deckA.ff',
  'deckA.rw',
  'deckA.pitchBendPlus',
  'deckA.pitchBendMinus',
  'deckB.play',
  'deckB.cue',
  'deckB.sync',
  'deckB.load',
  'deckB.pfl',
  'deckB.jog',
  'deckB.filter',
  'deckB.wet',
  'deckB.filterPad',
  'deckB.flangerPad',
  'deckB.pitch',
  'deckB.gain',
  'deckB.eqHigh',
  'deckB.eqMid',
  'deckB.eqLow',
  'deckB.killHigh',
  'deckB.killMid',
  'deckB.killLow',
  'deckB.ff',
  'deckB.rw',
  'deckB.pitchBendPlus',
  'deckB.pitchBendMinus',
  'mixer.faderA',
  'mixer.faderB',
  'mixer.master',
  'mixer.headMix',
  /** Software cue-bus level (after HeadMix). RMX2 physical phones vol is analog — no MIDI. */
  'mixer.phones',
  'mixer.crossfader',
  /** Vinyl — toggles jog dual-zone (on) vs single-zone rate nudge (off). */
  'mixer.vinyl',
  'browse.up',
  'browse.down',
  'browse.left',
  'browse.right',
] as const;

export type ControlId = (typeof CONTROL_IDS)[number];

export function isControlId(v: string): v is ControlId {
  return (CONTROL_IDS as readonly string[]).includes(v);
}
